### ISSUE TITLE
Upload package to PyPI

### ISSUE THREAD

**Issue by skorokithakis** [nixjdm/lektor-image-resize#1]
This package doesn't seem to actually be on PyPI? It would be great if it could be published there.

**Comment by nixjdm** [comment]
Hey @skorokithakis, I've been going through many plugins this last week, and I noticed this too as I was updating the other plugins I own / maintain. I know you've got image related interests. Do you remember this plugin well enough? Is it still useful? I haven't had enough time to read through it yet.

Thanks!

**Comment by skorokithakis** [comment]
Hey @nixjdm, I'm pretty sure my plugin supersedes this, as it has more features (and is maintained). The unavailability of this one is what led me to create mine, if I recall correctly.

**Comment by nixjdm** [comment]
That's about what I was wondering. I'll mark this one as no longer
maintained and recommend yours. Thanks!
